version: '3'

services:
   tailscale-derp:
       container_name: DERP-${TAILSCALE_HOSTNAME}
       image: tailscale-derp-docker:1.0
       hostname: ${TAILSCALE_HOSTNAME}
       volumes:
         - /lib/modules:/lib/modules:ro
         - $PWD/certs:/root/derper/ssl:rw
         - $PWD/config:/var/lib/tailscale
       env_file:
        - .env
       cap_add:
         - NET_ADMIN
       ports:
         # if use derp to get certs, make sure to expose the HTTP 80 port for ACME challenges
         #- 80:80/tcp
         - 443:443/tcp
         - 3478:3478/udp
         # sockets5 proxy port
         #- 10086:10086/tcp
       restart: unless-stopped
       networks:
         - ts-derp-net

networks:
  ts-derp-net:
    name: ts-derp-${TAILSCALE_HOSTNAME}-net
    driver: bridge




